// <auto-generated />
using Botflox.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Botflox.Bot.Migrations
{
    [DbContext(typeof(BotfloxDatabase))]
    [Migration("20200926193839_Verification")]
    partial class Verification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Botflox.Bot.Data.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("CommandPrefix")
                        .IsRequired()
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.HasKey("GuildId");

                    b.ToTable("GuildsSettings");
                });

            modelBuilder.Entity("Botflox.Bot.Data.UserSettings", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MainCharacter")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("VerifiedCharacter")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId");

                    b.HasIndex("MainCharacter")
                        .IsUnique();

                    b.ToTable("UsersSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
