name: Deploy

on:
  push:
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish BotfloxWeb -c release --no-restore -o dist
    - name: Stop Remote
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command:  sudo systemctl stop botflox
        username:  ${{ secrets.REMOTE_USER }}
        host:  ${{ secrets.REMOTE_HOST }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          DEPLOY_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ~/botflox
    - name: Start Remote
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command:  sudo systemctl start botflox
        username:  ${{ secrets.REMOTE_USER }}
        host:  ${{ secrets.REMOTE_HOST }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
